### ISSUE TITLE
1.20 experiment crash from newer smithing recipes

### ISSUE THREAD

**Issue by val-int1** [Skirlez/fabricated-exchange#1]
Attempting to create or load a world that has the 1.20 experiment datapack enabled causes the game to crash, as the pack contains the new `SmithingTrimRecipe` and `SmithingTransformRecipe` recipes, neither of which extends `LegacySmithingRecipe`. This does not happen if the experiment feature is not enabled.

Versions:
Minecraft: 1.19.4
Fabric API: 0.86.1+1.19.4
Fabricated Exchange: mc1.19.4-0.4.2

[Crash log](https://github.com/Skirlez/fabricated-exchange/files/12245154/crash-2023-08-02_23.58.27-server.txt)

**Comment by Skirlez** [comment]
I didn't even know that datapack was a thing. Pretty simple fix, will be out in the next release. Thank you for opening the issue!
