### ISSUE TITLE
Server Crash with Fabricated Exchange

### ISSUE THREAD

**Issue by redruM23232** [Skirlez/fabricated-exchange#12]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2023-11-23 21:16:08
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "java.util.HashMap.containsKey(Object)" because "this.value" is null
	at com.skirlez.fabricatedexchange.util.config.NbtItemsFile.hasItem(NbtItemsFile.java:39)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerNbt(EmcData.java:89)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerStackNbt(EmcData.java:82)
	at net.minecraft.class_1799.handler$ele000$fabricated-exchange$addEmcToTooltip(class_1799.java:9162)
	at net.minecraft.class_1799.method_7950(class_1799.java:835)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_490.method_25394(class_490.java:94)
	at net.minecraft.class_757.redirect$jjc000$renderer$dispatchScreenRender(class_757.java:13076)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.skirlez.fabricatedexchange.util.config.NbtItemsFile.hasItem(NbtItemsFile.java:39)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerNbt(EmcData.java:89)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerStackNbt(EmcData.java:82)
	at net.minecraft.class_1799.handler$ele000$fabricated-exchange$addEmcToTooltip(class_1799.java:9162)
	at net.minecraft.class_1799.method_7950(class_1799.java:835)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_490.method_25394(class_490.java:94)
	at net.minecraft.class_757.redirect$jjc000$renderer$dispatchScreenRender(class_757.java:13076)
Mixins in Stacktrace:
	net.minecraft.class_1799:
		ml.pkom.mcpitanlibarch.mixin.ItemStackMixin (mcpitanlibarch-common.mixins.json)
		net.id.paradiselost.mixin.item.ItemStackMixin (paradise_lost.mixins.json)
		io.github.apace100.calio.mixin.DontOverwriteAttrModsMixin (calio.mixins.json)
		net.fabricmc.fabric.mixin.item.client.ItemStackMixin (fabric-item-api-v1.client.mixins.json)
		dev.onyxstudios.cca.mixin.item.common.MixinItemStack (mixins.cardinal_components_item.json)
		io.github.fabricators_of_create.porting_lib.mixin.common.ItemStackMixin (porting_lib_base.mixins.json)
		net.merchantpug.apugli.mixin.ItemStackMixin (apugli.mixins.json)
		org.betterx.bclib.mixin.common.ItemStackMixin (bclib.mixins.common.json)
		me.frankv.staaaaaaaaaaaack.mixin.ItemStackAccessor (staaaaaaaaaaaack.mixins.json)
		eu.pb4.polymer.mixin.client.item.ItemStackMixin (polymer.mixins.json)
		org.betterx.betterend.mixin.client.ItemStackMixin (betterend.mixins.client.json)
		io.github.apace100.calio.mixin.CustomNonItalicNameMixin$ModifyItalicDisplayItem (calio.mixins.json)
		me.jellysquid.mods.lithium.mixin.block.hopper.ItemStackMixin (lithium.mixins.json)
		org.betterx.betternether.mixin.common.ItemStackMixin (betternether.mixins.common.json)
		draylar.inmis.mixin.ItemStackMixin (inmis.mixins.json)
		net.id.paradiselost.mixin.client.ItemStackMixin (paradise_lost.mixins.json)
		com.nhoryzon.mc.farmersdelight.mixin.LivingEntityOnUseItemFinishMixin (farmersdelight.mixins.json)
		net.bettercombat.mixin.ItemStackMixin (bettercombat.mixins.json)
		io.github.apace100.apoli.mixin.ItemStackMixin (apoli.mixins.json)
		me.steven.indrev.mixin.common.MixinItemStack (indrev.mixins.json)
		me.jellysquid.mods.lithium.mixin.item.ItemStackMixin (lithium.mixins.json)
		eu.pb4.polymer.mixin.item.ItemStackMixin (polymer.mixins.json)
		cc.unilock.sortedenchantments.mixin.ItemStackMixin (sortedenchantments.mixins.json)
		dev.emi.trinkets.mixin.ItemStackMixin (trinkets.mixins.json)
		de.dafuqs.spectrum.mixin.ItemStackMixin (spectrum.mixins.json)
		squeek.appleskin.mixin.ItemStackMixin (appleskin.mixins.json)
		net.devtech.stacc.mixin.SerializationFixin (stacc.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.ItemStackMixin (kubejs-common.mixins.json)
		com.natamus.collective.fabric.mixin.ItemStackMixin (collective_fabric.mixins.json)
		com.blamejared.crafttweaker.mixin.common.transform.item.MixinItemStackAttributes (crafttweaker.fabric.mixins.json)
		dev.emi.emi.mixin.ItemStackMixin (emi.mixins.json)
		net.fabricmc.fabric.mixin.item.ItemStackMixin (fabric-item-api-v1.mixins.json)
		io.github.apace100.originsclasses.mixin.ItemStackMixin (origins-classes.mixins.json)
		io.wispforest.owo.mixin.ItemStackMixin (owo.mixins.json)
		dev.emi.emi.mixin.conversion.ItemStackMixin (emi-fabric.mixins.json)
		com.skirlez.fabricatedexchange.mixin.client.ModItemStackTooltip (fabricated-exchange.client.mixins.json)
		com.nhoryzon.mc.farmersdelight.mixin.MigrationItemStackMixin (farmersdelight.mixins.json)
		de.guntram.mcmod.durabilityviewer.mixin.TooltipMixin (mixins.durabilityviewer.json)
		moriyashiine.extraorigins.mixin.ItemStackMixin (extraorigins.mixins.json)
	net.minecraft.class_437:
		dev.isxander.adaptivetooltips.mixins.ScreenMixin (adaptive-tooltips.mixins.json)
		appeng.mixins.WrappedGenericStackTooltipModIdMixin (ae2.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinScreen (fancymenu.general.mixin.json)
		net.fabricmc.fabric.mixin.client.rendering.ScreenMixin (fabric-rendering-v1.mixins.json)
		io.wispforest.owo.mixin.ui.layers.ScreenMixin (owo.mixins.json)
		com.minenash.seamless_loading_screen.mixin.ScreenMixin (seamless_loading_screen-common.mixins.json)
		dev.latvian.mods.kubejs.core.mixin.common.ScreenMixin (kubejs-common.mixins.json)
		net.blay09.mods.balm.mixin.ScreenAccessor (balm.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinScreen (konkrete.mixin.json)
		io.github.fabricators_of_create.porting_lib.mixin.client.ScreenMixin (porting_lib_base.mixins.json)
		it.hurts.sskirillss.nerb.mixin.ScreenMixin (nerb-common.mixins.json)
		net.fabricmc.fabric.mixin.screen.ScreenAccessor (fabric-screen-api-v1.mixins.json)
		vazkii.patchouli.mixin.client.AccessorScreen (patchouli_xplat.mixins.json)
		dev.architectury.mixin.fabric.client.MixinScreen (architectury.mixins.json)
		com.blamejared.controlling.mixin.AccessScreen (controlling.mixins.json)... (10 KB left)

**Comment by Skirlez** [comment]
Thank you for posting this issue, we have encountered this bug on the 1.19.2 version and it has yet to be fixed, it seems to happen inconsistently.
If you are playing on that version, did you do anything specific to trigger this? Any additional mods? Any information would be very helpful

**Comment by redruM23232** [comment]
Hi,

It was after I crafted a philosophers stone that it started happening.

There was no additional mods activated, other than the default mod list.

This has only happened on a server, rather than anything else.

Could it be to do with the configuration of the server in properties maybe
?

Thanks,

**Comment by Skirlez** [comment]
[attempted_fix.zip](https://github.com/Skirlez/fabricated-exchange/files/13462029/attempted_fix.zip)
Could you try using this version of the mod? This version is a bit more up to date including #11 and if it still crashes, please send the full server log

**Comment by redruM23232** [comment]
Hiya,

Thanks for sending this across. I'll try it on Sunday and let you know!

Have a lovely weekend.

**Comment by redruM23232** [comment]
Hiya,

This works and doesn't crash. However, I'm unable to acctually use items
such as the energy collector and I cant craft the transmutation table

**Comment by Skirlez** [comment]
Thank you for testing, glad the crash is fixed. As for the energy collector issue, here is another build which should fix that. A release with these fixes and the additional content will be put out soon.
[attempted_fix_2.zip](https://github.com/Skirlez/fabricated-exchange/files/13492749/attempted_fix_2.zip)


Also, the transmutation table recipe does not exist yet.

**Comment by Skirlez** [comment]
I'm really not sure what you mean. The energy collector can only accept fuel items (like Coal, Gunpowder, all the coal-like items in the Fabricated Exchange tab, etc) as input, and it upgrades their tier once it has collected enough EMC.

**Comment by cheesebobi** [comment]
Yo Skirlez pretty sure he meant the energy condenser, in the original mod you could put items in the MK1 Energy Condenser. I personally think the change you made to make it not possible in the MK1 is a good thing for balance but maybe adding an option for it would be a good idea

**Comment by Skirlez** [comment]
Closing as the bug(s) have been fixed.
