### ISSUE TITLE
Dont know hao to install.

### ISSUE THREAD

**Issue by MEMZ-Edge01** [Skirlez/fabricated-exchange#14]
I don't understand how to install,can you help me with it?

**Comment by Skirlez** [comment]
Just as you install any other mod, download through [Modrinth](https://modrinth.com/mod/fabricated-exchange) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fabricated-exchange), install [Fabric](https://fabricmc.net/) and drag the .jar of the mod to Minecraft's mod folder

**Comment by MEMZ-Edge01** [comment]
ok,i don't know that it has been loaded on curseforge and modrinth
