### ISSUE TITLE
Transmutation Table isn't craftable

### ISSUE THREAD

**Issue by Maks1234Ty** [Skirlez/fabricated-exchange#20]
Transmutation table isn't craftable (Version 0.6.0, Fabric 1.19.4) JEI does not show the recipy, and attemting to craft it manually with 4 obsidian in corners, 4 stones in between, middle is philosopher stone does not appear to yield any results

**Comment by Skirlez** [comment]
This is on purpose - I didn't implement it in yet because I'm still considering changing the mod's balance. I'll get around to it next release most likely.
