### ISSUE TITLE
Client crashes when I open inventory.

### ISSUE THREAD

**Issue by Raspiguy** [Skirlez/fabricated-exchange#22]
Hello.

I am using minecraft fabric 1.19.2 and mod version 0.5.3 on a server. I have installed the mod with no issues on the server however on my client, whenever i open my inventory my client crashes with error code -1. See full crash below. The main error it shows on the crash is   

**_java.lang.NullPointerException: Cannot invoke "java.util.HashMap.containsKey(Object)" because "this.value" is null_**

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-03-17 11:44:32
Description: Rendering screen

**_java.lang.NullPointerException: Cannot invoke "java.util.HashMap.containsKey(Object)" because "this.value" is null_**
	at com.skirlez.fabricatedexchange.util.config.NbtItemsFile.hasItem(NbtItemsFile.java:39)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerNbt(EmcData.java:89)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerStackNbt(EmcData.java:82)
	at net.minecraft.class_1799.handler$cbh000$fabricated-exchange$addEmcToTooltip(class_1799.java:3662)
	at net.minecraft.class_1799.method_7950(class_1799.java:835)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_490.method_25394(class_490.java:94)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.skirlez.fabricatedexchange.util.config.NbtItemsFile.hasItem(NbtItemsFile.java:39)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerNbt(EmcData.java:89)
	at com.skirlez.fabricatedexchange.emc.EmcData.considerStackNbt(EmcData.java:82)
	at net.minecraft.class_1799.handler$cbh000$fabricated-exchange$addEmcToTooltip(class_1799.java:3662)
	at net.minecraft.class_1799.method_7950(class_1799.java:835)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_490.method_25394(class_490.java:94)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (257, 171). Absolute: (1028.000000, 686.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['GingerTw0t'/256, l='ClientLevel', x=32.60, y=66.00, z=4.38]]
	Chunk stats: 16384, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,16), Section: (at 0,2,0 in 0,4,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6267146 game time, 752972 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Steam 'n' Rails Green Signals, Steam 'n' Rails Legacy Semaphores, FreshAnimations_v1.8.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1628109536 bytes (1552 MiB) / 3422552064 bytes (3264 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5176
	Graphics card #1 name: DisplayLink USB Device
	Graphics card #1 vendor: DisplayLink (0x17e9)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x6006
	Graphics card #1 versionInfo: DriverVersion=9.3.3324.0
	Graphics card #2 name: DisplayLink USB Device
	Graphics card #2 vendor: DisplayLink (0x17e9)
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: 0x6006
	Graphics card #2 versionInfo: DriverVersion=9.3.3324.0
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 42421.21
	Virtual memory used (MB): 19623.86
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 19.03
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.6
		appleskin: AppleSkin 2.5.1+mc1.19
		architectury: Architectury 6.6.92
		betteradvancements: Better Advancements 0.3.0.148
		betteranimations: Kelvin's Better Animations 1.0-SNAPSHOT
		betterf3: BetterF3 4.0.1
		chat_heads: Chat Heads 0.10.32
		chunkloaders: Chunk Loaders 1.2.8+a
		cloth-config: Cloth Config v8 8.3.115
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.40
		configured: Configured 2.0.0
		create: Create 0.5.1-f-build.1334+mc1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-8
			forge_tags: Porting Lib Tags 3.0
			forgeconfigapiport: Forge Config API Port 4.2.9
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib_accessors: Porting Lib Accessors 2.1.1282+1.19.2
			porting_lib_base: Porting Lib Base 2.1.1282+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1282+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.1282+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1282+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1282+1.19.2
				porting_lib_models: Porting Lib Models 2.1.1282+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			porting_lib_entity: Porting Lib Entity 2.1.1282+1.19.2
			porting_lib_extensions: Porting Lib Extensions 2.1.1282+1.19.2
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1282+1.19.2
			porting_lib_networking: Porting Lib Networking 2.1.1282+1.19.2
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1282+1.19.2
			porting_lib_transfer: Porting Lib Transfer 2.1.1282+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.1282+1.19.2
				porting_lib_common: Porting Lib Common 2.1.1282+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.1282+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.58-MC1.19.2
		create_jetpack: Create Jetpack 3.5.0
			flightlib: Flight Lib 1.2.0
		createaddition: Create Crafts & Additions 1.2.3
			team_reborn_energy: Energy 2.3.0
		createdeco: Create Deco 1.3.3-1.19.2
		distanthorizons: Distant Horizons 2.0.1-a
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entity_model_features: Entity Model Features 1.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		extended_drawers: Extended Drawers 1.4.5+mc.1.19.2
			graphlib: Graph Lib 0.3.6+1.19.2
			mconfig: Mconfig 1.2.0+mc.1.19-rc1
				de_poiu_apron_apron: apron 2.1.1
				fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-api: Fabric API 0.77.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+ee641e7390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.25+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.28+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+526f2c6790
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricated-exchange: Fabricated Exchange 0.5.3+1.19.2
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 5.0.3
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.9+mc1.19.2
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		ironchests: Iron Chests: Restocked 3.1.3
			resourcefullib: Resourceful Lib 1.1.20
		jade: Jade 8.7.3
		jadeaddons: Jade Addons 3.2.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1019
		journeymap: Journeymap 5.9.7p1
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		libipn: libIPN 4.0.1
		minecraft: Minecraft 1.19.2
		mobplaques: Mob Plaques 4.0.1
		modmenu: Mod Menu 4.2.0-beta.2
		mousetweaks: Mouse Tweaks 2.22
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		pickupnotifier: Pick Up Notifier 4.2.4
		piercingpaxels: Piercing Paxels 1.0.7
		player-animator: Player Animator 1.0.2
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		puzzleslib: Puzzles Lib 4.4.3
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		railways: Create: Steam 'n' Rails 1.5.3+fabric-mc1.19.2
			mm: Manningham Mills 2.3
		sfcr: SuperFancyClouds: Rearchitected 1.7.6-mc1.19.2
		simpleframes: Open Simple Frames 1.0.8
		skinlayers3d: 3d-Skin-Layers 1.6.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.3.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17
		swingthrough: SwingThrough 1.0.4+1.19
		tpshud: TPS Hud 1.6.0+1.19.2
			me_obsilabor_alert: alert 1.0.6
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.33
		vanillatweaks: VanillaTweaks 1.5.66
		visuality: Visuality 0.5.6
		visualworkbench: Visual Workbench 4.2.4
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.15.7-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Steam 'n' Rails Green Signals, Steam 'n' Rails Legacy Semaphores, file/FreshAnimations_v1.8.zip, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by Skirlez** [comment]
The 1.19.2 version is pretty outdated (we're on 1.19.4 now), and the mod won't be downgraded again most likely until development is finished... So unfortunately this will remain unfixed for now
