### ISSUE TITLE
Client crashes when connecting via LAN

### ISSUE THREAD

**Issue by TripStank** [Skirlez/fabricated-exchange#27]
Installed Fabricated Exchange on top of Tekxit 4, it works just fine for me, but my alt account connecting via LAN multiplayer (has the same exact mods as host installed in the mods folder) will load into the world, be fine for 1-5 minutes and crash. here is HIS (guest) crash log

[crash-2024-03-29_21.48.04-client.txt](https://github.com/Skirlez/fabricated-exchange/files/14810520/crash-2024-03-29_21.48.04-client.txt)

Any Help would be greatly appreciated, my host singleplayer game is running it with all the tekxit mods just fine and a guest can join but only for a few minutes before crashing.

**Comment by Skirlez** [comment]
This issue has been reported several times on 1.19.2, it's just that we moved on from it quite a while ago. Given this is the third(?) time it's been reported, I think I'm going to upload a fix for it, since evidently people are still playing that version.

**Comment by TripStank** [comment]
I can assure you that would make me and at LEAST 2 other people very happy xD.

 I can imagine many more legacy version players would sincerely appreciate the update.
 
 And thank you for making it in the first place!

**Comment by Skirlez** [comment]
https://modrinth.com/mod/fabricated-exchange/version/0.6.0+1.19.2
I will be very sad if the crash still happens. Please open another issue if it does.

**Comment by TripStank** [comment]
you absolutely rock! thanks :D :D :D
