### ISSUE TITLE
EMC values 

### ISSUE THREAD

**Issue by Dragonracer1973** [Skirlez/fabricated-exchange#4]
Sorry for back to back issues here. 
I had a whole rant on EMC. Then went back and reread yesterdays comment. 
I am derp. :p
Thnx again for the port.

**Comment by Skirlez** [comment]
Alright. By the way, next update will have EMC values for most vanilla items by default, thank's to @obslsessed's #3 pull request.

**Comment by Dragonracer1973** [comment]
awesome
