### ISSUE TITLE
Can not open worlds without crash

### ISSUE THREAD

**Issue by ChrisPBacon299** [Skirlez/fabricated-exchange#5]
As soon as i try to load a world with this mod i get a crash saying something about can not read field "orgin" because "equation" is null

**Comment by Skirlez** [comment]
Hello! Please send the error log that gets printed out with the crash, along with your game version and the list of mods you were using alongside this one (if any).

**Comment by Skirlez** [comment]
Closing as the EMC mapper has been rewritten at least once since this issue was opened...
